# Generated by Django 4.0.4 on 2022-04-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='')),
                ('from_language', models.CharField(max_length=100, verbose_name='From Language')),
                ('to_language', models.CharField(max_length=100, verbose_name='To Language')),
            ],
        ),
    ]
