# Generated by Django 4.0.4 on 2022-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedatato',
            name='image_url',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
