# Generated by Django 4.0.4 on 2022-04-16 13:53

from django.db import migrations, models
import imagesData.models


class Migration(migrations.Migration):

    dependencies = [
        ('imagesData', '0003_alter_imagedatato_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedatato',
            name='image_url',
            field=models.ImageField(upload_to=imagesData.models.upload_to),
        ),
    ]
